#spring boot file config
#spring.http.multipart.max-file-size=100MB
#spring.http.multipart.max-request-size=200MB
spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://uat.any-call.com:53306/anycall30?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: anycall30_readonly
    password: readonly!@#
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis
mybatis:
  type-aliases-package: com.platform.parent.mybatis.bean
  mapper-locations: classpath:mapper/*.xml


# jwt config
#jwt.header=Authorization
#jwt.secret=platformParentSecretKey
#jwt.expiration=259200
#jwt.token-head="Bearer "
jwt:
  header: Authorization
  secret: platformParentSecretKey
  expiration: 259200
  tokenHead: "Bearer "
#server:
#  port: 8081
#  ssl:
#    key-store: keystore.p12
#    key-store-password: mxjzqk
#    key-store-type: PKCS12
#    key-alias: tomcat
logging:
  file: ../logs/wechat.log